title: Angelo Vassallo (AngVas) personal site
email: angelovassallo123@proton.me
description: >- # questa è una descrizione breve del tuo sito
  My protfolio, projects and personal interests.
baseurl: "" # il subpath del tuo sito, ad es. /blog
url: "https://angelovassallo.github.io" # l'URL base del tuo sito
twitter_username: angelovassallo
github_username:  angelovassallo

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
